version: '3.9'

services:
  searchengine:
    image: searchengineip
    container_name: searchengine-containeripcom
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - redis
    volumes:
      - searchengine_logs:/app/logs
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  searchengine_logs:

networks:
  hostnet:
    external: true
    name: host